source/tutorialDjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^preguntas/$', 'preguntasyrespuestas.views.index', name='preguntas'),
    url(r'^preguntas/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_detalle', name='pregunta_detalle'),
    url(r'^preguntas/crear/$', 'preguntasyrespuestas.views.pregunta_crear', name='pregunta_crear'),
    url(r'^preguntas/editar/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_editar', name='pregunta_editar'),
]

source/preguntasyrespuestas/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone

# Create your models here.
class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()
	publicado_hoy.boolean = True
	publicado_hoy.descripcion_corta = "¿Preguntado hoy?"


class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField("Respuesta preferida", default=False)

	def __str__(self):
		return self.contenido

source/preguntasyrespuestas/views.py
#from django.shortcuts import render
from django.http import HttpResponse, Http404

from preguntasyrespuestas.models import Pregunta
from django.utils import timezone
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.template import RequestContext
from preguntasyrespuestas.form import PreguntaForm

# Create your views here.
def index(request):
	preguntas = Pregunta.objects.all()
	# respuesta_string = "Preguntas <br/>"
	# respuesta_string += '<br/>'.join(["id: %s, asunto: %s" % 
	# 	(p.id, p.asunto) for p in preguntas])
	# return HttpResponse(respuesta_string)
	#print render({'preguntas': preguntas}, 'detail.html')
	return render_to_response('preguntas.html',{'preguntas': preguntas})

def pregunta_detalle(request, pregunta_id):
	# try:
	# 	pregunta = Pregunta.objects.get(pk=pregunta_id)
	# except Pregunta.DoesNotExist as dne:
	# 	print dne
	# 	raise Http404
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	#return HttpResponse("%s?" % pregunta.asunto)
	return render_to_response('pregunta_detalle.html',{'pregunta': pregunta})

def pregunta_crear(request):
	if request.method == 'POST':
		form = PreguntaForm(request.POST)
		if form.is_valid():
			# pregunta = Pregunta(asunto=form.cleaned_data['asunto'],
			# 	descripcion=form.cleaned_data['descripcion'],
			# 	fecha_publicacion=timezone.now())
			# pregunta.save()
			form.save()
			return redirect('preguntas')
	else: 
		form = PreguntaForm()	
	return render_to_response('pregunta_crear.html', 
		{'form':form},
		context_instance=RequestContext(request)) #aseguracion de las variables mandados por HTTP

def pregunta_editar(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	if request.method == 'POST':
		form = PreguntaForm(request.POST, instance=pregunta)
		if form.is_valid():
			form.save()
			return redirect('pregunta_detalle', pregunta_id)
	else:
		form = PreguntaForm(instance=pregunta)
	return render_to_response('pregunta_editar.html',
		{'form': form},
		context_instance=RequestContext(request))

source/preguntasyrespuestas/templates/base.html
<meta charset="UTF-8">
<html>
<head>
	<title>Curso de Django | {% block title %}Inicio{% endblock %}</title>
</head>
<body>
	<div id="header">
		<h1>Curso de Django</h1>
	</div>
	<div id="content">
		{% block content %}{% endblock %}
	</div>
</body>
</html>

source/preguntasyrespuestas/templates/pregunta_crear.html
{% extends "base.html" %}
{% block title %}Crear una pregunta{% endblock %}
{% block content %}
	<form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit">
	</form>
{% endblock %}

source/preguntasyrespuestas/templates/pregunta_detalle.html
{% extends "base.html" %}
{% block title %} Detalle:{{ pregunta.id }} {% endblock %}
{% block content %}
	<h2>{{ pregunta.asunto }}?</h2>
	<p> <a href="{% url "pregunta_editar" pregunta.id %}">Editar esta pregunta</a> </p>
	<p><b>Publicado: </b> {{ pregunta.fecha_publicacion|date:"D, d/m/Y" }} </p>
	<p>
	{% if pregunta.descripcion %}
		{{pregunta.descripcion}}
	{% else %}
		No se ha incluido descripcion
	{% endif %}	
	</p>
	<h3>Respuestas</h3>
	<ul>
		{% for respuesta in pregunta.respuesta_set.all %}
		  <li>{{respuesta.contenido|safe}}</li>
		{% empty %}
		  <li>Aun no hay respuestas</li>
		{% endfor %}
	</ul>
{% endblock %}

source/preguntasyrespuestas/templates/pregunta_editar.html
{% extends "base.html" %}
{% block title %}Editar una pregunta{% endblock %}
{% block content %}
	<form action="" method="post">{% csrf_token %}
		{# form.as_p #}
		{% for field in form %}
			<div class="field_container">
				{{ field.errors }}
				{{ field.label_tag }} </br>
				{{ field }}
			</div>
		{% endfor %}
		<input type="submit" value="Submit">
	</form>
{% endblock %}

{{ form.asunto.errors }}

source/preguntasyrespuestas/templates/preguntas.html
{% extends "base.html" %}
{% block title %} Preguntas {% endblock %}
{% block content %}
	<p><a href="{% url 'pregunta_crear' %}">Crear una pregunta</a></p>
	{% for pregunta in preguntas %}
		<a href="{% url 'pregunta_detalle' pregunta.id %}">{{ pregunta.asunto }}?</a><br/>
	{% empty %}
		Aun no existen preguntas
	{% endfor %}
{% endblock %}